### ISSUE TITLE
Relative v. Fully qualified class names

### ISSUE THREAD

**Issue by eevans** [hknustwmf/cassandra-table-properties#3]
Specifying a Java class (compression, compaction, replication strategy), is a means of plug-ability.  Stripping the package names will break anything not shipped with Cassandra (and we have used out-of-tree compaction algorithms in the past).

This is a pretty example of avoiding (wherever possible) any special-casing, and letting Cassandra validate any in appropriate input (where input here means the output of this utility). 

https://github.com/hknustwmf/cassandra-table-properties/blob/25813a23672a97ff549753437ea2c677b63731ef/table_properties/db.py#L285

**Comment by hknustwmf** [comment]
The problem here is the property comparison which this was meant to make easier. Most examples on the web  just show  the class name. I'll need to add extra code to figure out if the short name is the same as the FQCN.

**Comment by eevans** [comment]
I'm not sure I follow: Are saying that a short-form name in the config will
fail comparison with the DB (I guess it's always fully qualified there)?
Is so, we can just mandate (document) that you should use the fully
qualified form.

**Comment by hknustwmf** [comment]
The database returns the FQCN. I don't want to mandate that users have to remember the module names (horrible UX). What I just discussed with Will was that the user can either pick the FQCN or just the classname. For our purposes `org.apache.cassandra.locator.SimpleStrategy` can be written as   `SimpleStrategy` in YAML and not cause any change statements.

``` keyspace_name      | durable_writes | replication
--------------------+----------------+-------------------------------------------------------------------------------------
        system_auth |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '1'}
```

**Comment by willdoran** [comment]
For the record, I am also in favour of forcing specification of full class path, I'm not positive we want to add complexity around this if there is a simpler solution.

**Comment by hknustwmf** [comment]
Either org.apache.cassandra.locator.SimpleStrategy or SimpleStrategy are acceptable in the YAML config and won't trigger ALTER statements.
